// Parity tests for `src/nin_selector.rs` vs `core/nin_selector.py`.
//
// Follows the same JSON-payload-via-argv pattern established in
// `iran_bridge_prioritizer_parity.rs`: all test data is serialized to one
// JSON blob and passed as `sys.argv[1]`, so no Python source text is ever
// generated by hand-formatting Rust values into Python literals.
//
// Coverage:
// * `is_nin_eligible` over every branch: non-survivable transport,
//   `iran_asn_blocked` rejection, the `NIN_MIN_SCORE` boundary (0.39 vs
//   0.40 vs 0.41), snowflake auto-pass, webtunnel/meek_lite CDN-domain
//   match (via `host`), CDN-ASN match (via `asn`), CDN-domain match via
//   the raw bridge line, the `domain_front_cdn_ok` flag, and the
//   `composite_score`-present-as-explicit-`null` error path (compared as
//   "both sides fail", since Rust surfaces this as `Result::Err` rather
//   than a JSON value — see below).
// * `rescore_for_nin` over the multiplier table, the `round(min(1.0,
//   x*m), 4)` clamp-then-round order (using a value that overshoots 1.0
//   before clamping), descending-sort-with-preserved-ties, and
//   non-mutation of the input.
// * `build_nin_pack`: empty-input short-circuit shape, the full
//   3-file-write path (pack .txt + eligible.json + summary.json) with
//   content compared field-by-field EXCLUDING the wall-clock-dependent
//   `generated_at`/`# Generated:` fields (see the module-level doc
//   comment on `nin_selector.rs` for why those are not directly
//   comparable), and first-seen-wins dedup ordering across the two input
//   paths.
//
// `is_nin_eligible`/`rescore_for_nin` return `Result` on the Rust side
// (see `NinSelectorError`); the Python originals raise an uncaught
// `TypeError` for the equivalent malformed input instead of returning an
// error value. Tests for that path assert Python's subprocess call fails
// (non-zero exit / exception) and Rust's call returns `Err`, rather than
// comparing two JSON values — there is no successful Python return value
// to compare against for that input.

use std::path::Path;
use std::process::Command;

use chrono::Utc;
use serde_json::{json, Map, Value};

use torshield_ir_ultra::nin_selector::{
    build_nin_pack_with_paths, is_nin_eligible, rescore_for_nin,
};

// ─────────────────────────────────────────────────────────────────────────────
// Python helper
// ─────────────────────────────────────────────────────────────────────────────

fn python_executable() -> &'static str {
    if let Ok(path) = std::env::var("PYTHON") {
        return Box::leak(path.into_boxed_str());
    }
    "python3"
}

struct PythonResult {
    success: bool,
    stdout: String,
    stderr: String,
}

fn run_python_script(script: &str, payload: &Value) -> PythonResult {
    let payload_json = serde_json::to_string(payload).expect("payload must serialize");
    let repo_root = env!("CARGO_MANIFEST_DIR");
    let output = Command::new(python_executable())
        .current_dir(repo_root)
        .env("PYTHONPATH", repo_root)
        .arg("-c")
        .arg(script)
        .arg(&payload_json)
        .output()
        .unwrap_or_else(|err| panic!("python helper must execute: {err}"));
    PythonResult {
        success: output.status.success(),
        stdout: String::from_utf8_lossy(&output.stdout).to_string(),
        stderr: String::from_utf8_lossy(&output.stderr).to_string(),
    }
}

fn run_python_json(script: &str, payload: &Value) -> Value {
    let result = run_python_script(script, payload);
    assert!(result.success, "python helper failed: {}", result.stderr);
    serde_json::from_str(&result.stdout).unwrap_or_else(|err| {
        panic!(
            "python helper must emit JSON: {err}; stdout={}",
            result.stdout
        )
    })
}

const IS_ELIGIBLE_SCRIPT: &str = r##"
import json, sys
import core.nin_selector as ns

payload = json.loads(sys.argv[1])
result = ns.is_nin_eligible(payload["record"])
print(json.dumps(result))
"##;

const RESCORE_SCRIPT: &str = r##"
import json, sys
import core.nin_selector as ns

payload = json.loads(sys.argv[1])
result = ns.rescore_for_nin(payload["records"])
print(json.dumps(result, sort_keys=True, separators=(",", ":")))
"##;

fn python_is_nin_eligible(record: &Value) -> PythonResult {
    let payload = json!({ "record": record });
    run_python_script(IS_ELIGIBLE_SCRIPT, &payload)
}

fn python_rescore_for_nin(records: &[Value]) -> Value {
    let payload = json!({ "records": records });
    run_python_json(RESCORE_SCRIPT, &payload)
}

// ─────────────────────────────────────────────────────────────────────────────
// Rust-side helpers
// ─────────────────────────────────────────────────────────────────────────────

fn as_map(v: &Value) -> Map<String, Value> {
    v.as_object().unwrap().clone()
}

// ─────────────────────────────────────────────────────────────────────────────
// is_nin_eligible
// ─────────────────────────────────────────────────────────────────────────────

macro_rules! parity_eligible {
    ($name:ident, $record:expr) => {
        #[test]
        fn $name() {
            let record = $record;
            let py = python_is_nin_eligible(&record);
            assert!(py.success, "python call failed unexpectedly: {}", py.stderr);
            let py_value: bool =
                serde_json::from_str(py.stdout.trim()).expect("python must emit a JSON bool");
            let rs_value = is_nin_eligible(&as_map(&record)).expect("rust call must succeed");
            assert_eq!(py_value, rs_value);
        }
    };
}

parity_eligible!(
    parity_snowflake_passes_on_score_alone,
    json!({"transport": "snowflake", "composite_score": 0.5})
);
parity_eligible!(
    parity_non_survivable_transport_rejected,
    json!({"transport": "obfs4", "composite_score": 0.9})
);
parity_eligible!(
    parity_vanilla_rejected,
    json!({"transport": "vanilla", "composite_score": 0.99})
);
parity_eligible!(
    parity_unknown_transport_rejected,
    json!({"transport": "totally-unknown", "composite_score": 0.99})
);
parity_eligible!(
    parity_iran_asn_blocked_rejected,
    json!({"transport": "snowflake", "iran_status": "iran_asn_blocked", "composite_score": 0.9})
);
parity_eligible!(
    parity_score_just_below_threshold,
    json!({"transport": "snowflake", "composite_score": 0.39})
);
parity_eligible!(
    parity_score_at_threshold_boundary,
    json!({"transport": "snowflake", "composite_score": 0.40})
);
parity_eligible!(
    parity_score_just_above_threshold,
    json!({"transport": "snowflake", "composite_score": 0.41})
);
parity_eligible!(
    parity_webtunnel_cdn_host_match,
    json!({"transport": "webtunnel", "composite_score": 0.9, "host": "edge.fastly.net"})
);
parity_eligible!(
    parity_webtunnel_non_cdn_host_rejected,
    json!({"transport": "webtunnel", "composite_score": 0.9, "host": "random.example.com"})
);
parity_eligible!(
    parity_meek_lite_cdn_asn_match,
    json!({"transport": "meek_lite", "composite_score": 0.9, "asn": "as8075"})
);
parity_eligible!(
    parity_asn_case_insensitive,
    json!({"transport": "webtunnel", "composite_score": 0.9, "asn": "AS13335"})
);
parity_eligible!(
    parity_webtunnel_raw_line_cdn_match,
    json!({
        "transport": "webtunnel", "composite_score": 0.9,
        "line": "webtunnel 1.2.3.4:443 url=https://x.cloudfront.net"
    })
);
parity_eligible!(
    parity_domain_front_flag_match,
    json!({"transport": "webtunnel", "composite_score": 0.9, "flags": ["domain_front_cdn_ok"]})
);
parity_eligible!(
    parity_domain_front_flag_absent_among_others,
    json!({"transport": "webtunnel", "composite_score": 0.9, "flags": ["some_other_flag"]})
);
parity_eligible!(
    parity_score_falls_back_to_score_field,
    json!({"transport": "snowflake", "score": 0.9})
);
parity_eligible!(
    parity_missing_score_defaults_zero,
    json!({"transport": "snowflake"})
);
parity_eligible!(
    parity_composite_score_prioritized_over_score,
    json!({"transport": "snowflake", "composite_score": 0.1, "score": 0.9})
);
parity_eligible!(
    parity_transport_uppercase_normalized,
    json!({"transport": "SNOWFLAKE", "composite_score": 0.9})
);
parity_eligible!(
    parity_missing_transport_rejected,
    json!({"composite_score": 0.9})
);
parity_eligible!(
    parity_domain_arvancloud_ir_match,
    json!({"transport": "webtunnel", "composite_score": 0.9, "host": "edge.arvancloud.ir"})
);
parity_eligible!(
    parity_domain_azureedge_match,
    json!({"transport": "meek_lite", "composite_score": 0.9, "host": "bridge.azureedge.net"})
);

#[test]
fn parity_composite_score_explicit_null_fails_on_both_sides() {
    // Python: `float(None)` raises TypeError, propagating uncaught out of
    // `is_nin_eligible` -> the subprocess exits non-zero. Rust: the same
    // input yields `Err(NinSelectorError::NonNumericScore)`. There is no
    // successful value from either side to compare — both must fail.
    let record = json!({"transport": "snowflake", "composite_score": Value::Null});
    let py = python_is_nin_eligible(&record);
    assert!(
        !py.success,
        "python call was expected to raise but succeeded: {}",
        py.stdout
    );
    assert!(
        py.stderr.contains("TypeError"),
        "expected a TypeError, got: {}",
        py.stderr
    );

    let rs_result = is_nin_eligible(&as_map(&record));
    assert!(
        rs_result.is_err(),
        "rust call was expected to fail but returned Ok"
    );
}

#[test]
fn parity_non_numeric_score_string_fails_on_both_sides() {
    let record = json!({"transport": "snowflake", "composite_score": "not-a-number"});
    let py = python_is_nin_eligible(&record);
    assert!(!py.success);
    assert!(
        py.stderr.contains("ValueError"),
        "expected a ValueError, got: {}",
        py.stderr
    );

    let rs_result = is_nin_eligible(&as_map(&record));
    assert!(rs_result.is_err());
}

// ─────────────────────────────────────────────────────────────────────────────
// rescore_for_nin
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn parity_rescore_basic_multiplier_and_sort() {
    let records = vec![
        json!({"id": "a", "transport": "vanilla", "composite_score": 0.9}),
        json!({"id": "b", "transport": "snowflake", "composite_score": 0.5}),
        json!({"id": "c", "transport": "obfs4", "composite_score": 0.8}),
    ];
    let py = python_rescore_for_nin(&records);
    let rs_maps = rescore_for_nin(&records.iter().map(as_map).collect::<Vec<_>>())
        .expect("rust call must succeed");
    let rs = Value::Array(rs_maps.into_iter().map(Value::Object).collect());
    assert_eq!(py, rs);
}

#[test]
fn parity_rescore_clamps_overshoot_to_one() {
    // snowflake multiplier 1.5 * 0.9 = 1.35 -> must clamp to 1.0, testing
    // the clamp-then-round vs round-then-clamp order explicitly.
    let records = vec![json!({"transport": "snowflake", "composite_score": 0.9})];
    let py = python_rescore_for_nin(&records);
    let rs_maps = rescore_for_nin(&records.iter().map(as_map).collect::<Vec<_>>()).unwrap();
    let rs = Value::Array(rs_maps.into_iter().map(Value::Object).collect());
    assert_eq!(py, rs);
    assert_eq!(py[0]["nin_score"], json!(1.0));
}

#[test]
fn parity_rescore_unknown_transport_default_multiplier() {
    let records = vec![json!({"transport": "some-future-transport", "composite_score": 0.6})];
    let py = python_rescore_for_nin(&records);
    let rs_maps = rescore_for_nin(&records.iter().map(as_map).collect::<Vec<_>>()).unwrap();
    let rs = Value::Array(rs_maps.into_iter().map(Value::Object).collect());
    assert_eq!(py, rs);
}

#[test]
fn parity_rescore_missing_transport_defaults_unknown() {
    let records = vec![json!({"composite_score": 0.6})];
    let py = python_rescore_for_nin(&records);
    let rs_maps = rescore_for_nin(&records.iter().map(as_map).collect::<Vec<_>>()).unwrap();
    let rs = Value::Array(rs_maps.into_iter().map(Value::Object).collect());
    assert_eq!(py, rs);
}

#[test]
fn parity_rescore_ties_preserve_original_order() {
    let records = vec![
        json!({"id": 0, "transport": "obfs4", "composite_score": 1.0}),
        json!({"id": 1, "transport": "obfs4", "composite_score": 1.0}),
        json!({"id": 2, "transport": "obfs4", "composite_score": 1.0}),
    ];
    let py = python_rescore_for_nin(&records);
    let rs_maps = rescore_for_nin(&records.iter().map(as_map).collect::<Vec<_>>()).unwrap();
    let rs = Value::Array(rs_maps.into_iter().map(Value::Object).collect());
    assert_eq!(py, rs);
    let py_ids: Vec<i64> = py
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r["id"].as_i64().unwrap())
        .collect();
    assert_eq!(py_ids, vec![0, 1, 2]);
}

#[test]
fn parity_rescore_field_preservation() {
    let records = vec![json!({
        "transport": "webtunnel",
        "composite_score": 0.7,
        "custom_field": "must survive",
        "nested": {"a": 1}
    })];
    let py = python_rescore_for_nin(&records);
    let rs_maps = rescore_for_nin(&records.iter().map(as_map).collect::<Vec<_>>()).unwrap();
    let rs = Value::Array(rs_maps.into_iter().map(Value::Object).collect());
    assert_eq!(py, rs);
    assert_eq!(py[0]["custom_field"], json!("must survive"));
}

#[test]
fn rescore_for_nin_does_not_mutate_input_rust_only() {
    let records = vec![as_map(
        &json!({"transport": "snowflake", "composite_score": 0.5}),
    )];
    let before = records.clone();
    let _ = rescore_for_nin(&records).unwrap();
    assert_eq!(records, before);
}

// ─────────────────────────────────────────────────────────────────────────────
// build_nin_pack — full I/O path
// ─────────────────────────────────────────────────────────────────────────────

fn unique_tmp_dir(label: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "nin_selector_parity_{}_{}_{}",
        label,
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

const BUILD_PACK_SCRIPT: &str = r##"
import json, sys
from pathlib import Path
import core.nin_selector as ns

payload = json.loads(sys.argv[1])
tmp = Path(payload["tmp_dir"])
ns.LATEST_RESULTS_PATH = tmp / "latest.json"
ns.IRAN_RESULTS_PATH = tmp / "iran.json"
ns.EXPORT_DIR = tmp / "export"
ns.DATA_DIR = tmp / "data"
ns.EXPORT_DIR.mkdir(parents=True, exist_ok=True)
ns.DATA_DIR.mkdir(parents=True, exist_ok=True)

ns.LATEST_RESULTS_PATH.write_text(json.dumps(payload["latest"]))
ns.IRAN_RESULTS_PATH.write_text(json.dumps(payload["iran"]))

summary = ns.build_nin_pack()

pack_file = ns.EXPORT_DIR / "iran_cut_pack.txt"
eligible_file = ns.DATA_DIR / "nin_eligible.json"

if pack_file.exists():
    pack_text = pack_file.read_text()
    # Strip the wall-clock-dependent line so the pack file body is comparable.
    pack_lines = [l for l in pack_text.split("\n") if not l.startswith("# Generated:")]
    pack_body = "\n".join(pack_lines)
else:
    # Empty-input short circuit in build_nin_pack() returns before ever
    # writing this file — matches the Rust side's `unwrap_or_default()`.
    pack_body = ""

eligible_json = json.loads(eligible_file.read_text()) if eligible_file.exists() else []

out = {
    "summary_stable_fields": {
        k: v for k, v in summary.items() if k not in ("generated_at", "pack_path")
    },
    "pack_body": pack_body,
    "eligible_json": eligible_json,
}
print(json.dumps(out, sort_keys=True, separators=(",", ":")))
"##;

fn rust_build_pack_normalized(tmp: &Path, latest: &Value, iran: &Value) -> Value {
    std::fs::create_dir_all(tmp).unwrap();
    let latest_path = tmp.join("latest.json");
    let iran_path = tmp.join("iran.json");
    let export_dir = tmp.join("export");
    let data_dir = tmp.join("data");
    std::fs::write(&latest_path, serde_json::to_string(latest).unwrap()).unwrap();
    std::fs::write(&iran_path, serde_json::to_string(iran).unwrap()).unwrap();

    let now = Utc::now();
    let summary = build_nin_pack_with_paths(&latest_path, &iran_path, &export_dir, &data_dir, now)
        .expect("rust build_nin_pack_with_paths must succeed");

    let pack_text =
        std::fs::read_to_string(export_dir.join("iran_cut_pack.txt")).unwrap_or_default();
    let pack_body: String = pack_text
        .split('\n')
        .filter(|l| !l.starts_with("# Generated:"))
        .collect::<Vec<_>>()
        .join("\n");
    let eligible_json: Value = if data_dir.join("nin_eligible.json").exists() {
        serde_json::from_str(&std::fs::read_to_string(data_dir.join("nin_eligible.json")).unwrap())
            .unwrap()
    } else {
        json!([])
    };

    let mut summary_map = summary.as_object().cloned().unwrap_or_default();
    summary_map.remove("generated_at");
    summary_map.remove("pack_path");

    json!({
        "summary_stable_fields": summary_map,
        "pack_body": pack_body,
        "eligible_json": eligible_json,
    })
}

#[test]
fn parity_build_nin_pack_empty_input() {
    let tmp = unique_tmp_dir("empty");
    let latest = json!({"bridges": []});
    let iran = json!({"bridges": []});

    let payload = json!({
        "tmp_dir": tmp.join("py").display().to_string(),
        "latest": latest,
        "iran": iran,
    });
    std::fs::create_dir_all(tmp.join("py")).unwrap();
    let py = run_python_json(BUILD_PACK_SCRIPT, &payload);

    let rs = rust_build_pack_normalized(&tmp.join("rs"), &latest, &iran);

    // Empty-input short circuit returns {"eligible": 0, "total": 0} on
    // BOTH sides (not the full summary shape) — pack/eligible files are
    // never written in that branch on either side.
    assert_eq!(
        py["summary_stable_fields"],
        json!({"eligible": 0, "total": 0})
    );
    assert_eq!(
        rs["summary_stable_fields"],
        json!({"eligible": 0, "total": 0})
    );

    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn parity_build_nin_pack_full_pipeline() {
    let tmp = unique_tmp_dir("full");
    let latest = json!({"bridges": [
        {"line": "snowflake url=https://x abc", "transport": "snowflake", "composite_score": 0.9},
        {"line": "webtunnel 1.2.3.4:443 url=https://y.fastly.net", "transport": "webtunnel", "composite_score": 0.7, "host": "y.fastly.net"},
        {"line": "obfs4 5.6.7.8:443 DEADBEEF", "transport": "obfs4", "composite_score": 0.95},
        {"line": "snowflake url=https://x abc", "transport": "snowflake", "composite_score": 0.1}
    ]});
    let iran = json!({"bridges": [
        {"line": "meek_lite azureedge.net", "transport": "meek_lite", "composite_score": 0.8, "host": "bridge.azureedge.net"}
    ]});

    let payload = json!({
        "tmp_dir": tmp.join("py").display().to_string(),
        "latest": latest,
        "iran": iran,
    });
    std::fs::create_dir_all(tmp.join("py")).unwrap();
    let py = run_python_json(BUILD_PACK_SCRIPT, &payload);
    let rs = rust_build_pack_normalized(&tmp.join("rs"), &latest, &iran);

    assert_eq!(py, rs);

    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn parity_build_nin_pack_dedup_first_seen_wins() {
    let tmp = unique_tmp_dir("dedup");
    // Same "line" key present in both files with different scores;
    // LATEST_RESULTS_PATH is read first, so its version must win.
    let latest = json!({"bridges": [
        {"line": "snowflake url=https://x abc", "transport": "snowflake", "composite_score": 0.9, "source_tag": "latest"}
    ]});
    let iran = json!({"bridges": [
        {"line": "snowflake url=https://x abc", "transport": "snowflake", "composite_score": 0.1, "source_tag": "iran"}
    ]});

    let payload = json!({
        "tmp_dir": tmp.join("py").display().to_string(),
        "latest": latest,
        "iran": iran,
    });
    std::fs::create_dir_all(tmp.join("py")).unwrap();
    let py = run_python_json(BUILD_PACK_SCRIPT, &payload);
    let rs = rust_build_pack_normalized(&tmp.join("rs"), &latest, &iran);

    assert_eq!(py, rs);
    assert_eq!(
        py["eligible_json"][0]["source_tag"],
        json!("latest"),
        "first-seen-wins must prefer LATEST_RESULTS_PATH's version"
    );

    let _ = std::fs::remove_dir_all(&tmp);
}
