from __future__ import annotations

"""
Auto-generated by TorShield-IR Zero-Error Engine v5.0
CI-safe pytest: skips network/tor/iran tests when SKIP_NETWORK_TESTS=true
"""

import os

import pytest

# Additive: enable permissive preflight mode during tests so unit tests
# using synthetic credentials (e.g. CF_ACCOUNT_ID_1="test-account-123")
# can exercise the downstream HTTP retry path without being rejected by
# the strict production preflight rules. This env var is read by
# _preflight_screen_slot() and preflight_validate_cf_slot().
os.environ.setdefault("TORSHIELD_PREFLIGHT_MODE", "permissive")


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line("markers", "network: requires live network or Tor")
    config.addinivalue_line("markers", "tor: requires a running Tor daemon")
    config.addinivalue_line("markers", "iran_bridge: requires Iran-reachable bridge")
    config.addinivalue_line("markers", "dpi: requires DPI-evasion environment")
    config.addinivalue_line("markers", "nin: requires NIN internet-cut detection")
    config.addinivalue_line("markers", "slow: marks test as slow (>30 s)")
    config.addinivalue_line("markers", "iran: requires Iran-specific network context")


def pytest_collection_modifyitems(
    config: pytest.Config, items: list[pytest.Item]
) -> None:
    if os.getenv("SKIP_NETWORK_TESTS", "false").lower() != "true":
        return
    skip = pytest.mark.skip(reason="SKIP_NETWORK_TESTS=true (CI mode)")
    _SKIP_MARKS = frozenset(
        {"network", "tor", "iran_bridge", "bridge", "dpi", "nin", "iran"}
    )
    for item in items:
        if _SKIP_MARKS.intersection(item.keywords):
            item.add_marker(skip)
