#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# scripts/circleci_env_bootstrap.sh
# ─────────────────────────────────────────────────────────────────────────────
# Materialise a runtime .env from CircleCI Context environment variables.
#
# Every KEY= line in configs/env_template.sh is emitted to the runtime .env.
# CircleCI Context values win; otherwise the template default is used. This is
# important for non-secret numeric settings such as MAX_WORKERS and timeout
# values: writing them as empty strings makes Python int()/float() config reads
# fail before their os.getenv(..., default) fallbacks can apply.
#
# SAFETY:
#   - The script NEVER prints secret values to stdout (only names/counts).
#   - The .env file is chmod 600 and never persisted as an artifact.
#   - Values are shell-escaped before being written to keep .env syntax valid.
# ════════════════════════════════════════════════════════════════════════════
set -euo pipefail

ENV_FILE="${1:-.env}"
TEMPLATE="${2:-configs/env_template.sh}"

if [ ! -f "$TEMPLATE" ]; then
    echo "FATAL: template $TEMPLATE not found" >&2
    exit 1
fi

quote_env_value() {
    # Emit a shell-compatible quoted value. python-dotenv understands this
    # format, and it safely preserves whitespace, #, $, quotes, and newlines.
    printf '%q' "$1"
}

extract_template_value() {
    local raw="$1"

    # Remove inline comments from the known template format. The template uses
    # comments after quoted/simple literals only; keeping this parser local makes
    # bootstrap deterministic and avoids sourcing arbitrary template code.
    raw="${raw%%#*}"
    raw="${raw%$'\r'}"

    # Trim leading/trailing whitespace around the default value.
    raw="${raw#${raw%%[![:space:]]*}}"
    raw="${raw%${raw##*[![:space:]]}}"

    # Unwrap one matching quote pair from defaults such as "150" or ''.
    if [[ ${#raw} -ge 2 ]]; then
        if [[ "${raw:0:1}" == '"' && "${raw: -1}" == '"' ]]; then
            raw="${raw:1:${#raw}-2}"
        elif [[ "${raw:0:1}" == "'" && "${raw: -1}" == "'" ]]; then
            raw="${raw:1:${#raw}-2}"
        fi
    fi

    printf '%s' "$raw"
}

echo "→ Materialising $ENV_FILE from CircleCI Context variables..."

cat > "$ENV_FILE" <<'HEADER'
# ════════════════════════════════════════════════════════════════════════════
# AUTO-GENERATED by scripts/circleci_env_bootstrap.sh
# Source: CircleCI Context `torshield-ir-secrets` + configs/env_template.sh
# DO NOT EDIT BY HAND — edit the Context/template instead:
#   https://app.circleci.com/settings/organization/<org>/contexts
# ════════════════════════════════════════════════════════════════════════════
HEADER

context_written=0
default_written=0
empty_written=0
while IFS= read -r line; do
    stripped="${line#\#}"
    stripped="${stripped#${stripped%%[![:space:]]*}}"
    case "$stripped" in
        *=*)
            key="${stripped%%=*}"
            key="${key%${key##*[![:space:]]}}"
            if [[ ! "$key" =~ ^[A-Z][A-Z0-9_]+$ ]]; then
                continue
            fi

            template_default="$(extract_template_value "${stripped#*=}")"
            if [ "${!key+x}" = "x" ]; then
                val="${!key}"
                context_written=$((context_written + 1))
            else
                val="$template_default"
                if [ -n "$val" ]; then
                    default_written=$((default_written + 1))
                else
                    empty_written=$((empty_written + 1))
                fi
            fi

            printf '%s=%s\n' "$key" "$(quote_env_value "$val")" >> "$ENV_FILE"
            ;;
    esac
done < "$TEMPLATE"

cat >> "$ENV_FILE" <<RUNTIME

# ─────────────────────────────────────────────────────────────────────────────
# CircleCI runtime (auto-populated, do not override in Context)
# ─────────────────────────────────────────────────────────────────────────────
CI=true
CI_PROVIDER=circleci
CIRCLE_BUILD_URL=$(quote_env_value "${CIRCLE_BUILD_URL:-}")
CIRCLE_PROJECT_REPONAME=$(quote_env_value "${CIRCLE_PROJECT_REPONAME:-}")
CIRCLE_BRANCH=$(quote_env_value "${CIRCLE_BRANCH:-main}")
CIRCLE_SHA1=$(quote_env_value "${CIRCLE_SHA1:-}")
RUNTIME

chmod 600 "$ENV_FILE"

echo "✓ Wrote $ENV_FILE"
echo "  Entries from Context : $context_written"
echo "  Template defaults    : $default_written"
echo "  Entries empty        : $empty_written  (set secret/runtime-only values in the Context if used)"

echo
echo "→ Empty vars (need Context entries if used by this job):"
while IFS= read -r line; do
    case "$line" in
        *=*)
            key="${line%%=*}"
            val="${line#*=}"
            if [ -z "$val" ] && [ "$key" != "CI" ] && [ "$key" != "CI_PROVIDER" ]; then
                echo "    - $key"
            fi
            ;;
    esac
done < "$ENV_FILE" | sort -u | head -50
