#!/usr/bin/env python3
"""
Auto-Generate Deployment Report for Tor-Bridges-Collector.

Produces a comprehensive deployment report including:
- Environment requirements
- Configuration checklist
- Service dependencies
- Deployment steps
- Health verification procedures
- Rollback procedures

Usage:
    python scripts/generate_deployment_report.py [--output docs/DEPLOYMENT_REPORT.md]
"""

import platform
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "DEPLOYMENT_REPORT.md"


def get_python_version() -> str:
    return f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"


def get_system_info() -> dict:
    """Gather system information."""
    info = {
        "python_version": get_python_version(),
        "platform": platform.platform(),
        "architecture": platform.machine(),
        "os": platform.system(),
    }

    # Check for Go
    try:
        go_ver = subprocess.run(["go", "version"], capture_output=True, text=True, timeout=5)
        info["go_version"] = go_ver.stdout.strip() if go_ver.returncode == 0 else "Not installed"
    except (FileNotFoundError, subprocess.TimeoutExpired) as _remediation_exc:
        from monitoring.structured_logger import record_silent_failure
        record_silent_failure('scripts.generate_deployment_report:43', _remediation_exc)
        info["go_version"] = "Not installed"

    # Check for Rust
    try:
        rust_ver = subprocess.run(["rustc", "--version"], capture_output=True, text=True, timeout=5)
        info["rust_version"] = rust_ver.stdout.strip() if rust_ver.returncode == 0 else "Not installed"
    except (FileNotFoundError, subprocess.TimeoutExpired) as _remediation_exc:
        from monitoring.structured_logger import record_silent_failure
        record_silent_failure('scripts.generate_deployment_report:50', _remediation_exc)
        info["rust_version"] = "Not installed"

    # Check for Zig
    try:
        zig_ver = subprocess.run(["zig", "version"], capture_output=True, text=True, timeout=5)
        info["zig_version"] = zig_ver.stdout.strip() if zig_ver.returncode == 0 else "Not installed"
    except (FileNotFoundError, subprocess.TimeoutExpired) as _remediation_exc:
        from monitoring.structured_logger import record_silent_failure
        record_silent_failure('scripts.generate_deployment_report:57', _remediation_exc)
        info["zig_version"] = "Not installed"

    return info


def parse_requirements(requirements_path: Path) -> list[dict]:
    """Parse requirements.txt into structured list."""
    deps = []
    if not requirements_path.exists():
        return deps
    for line in requirements_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Simple parsing: name[extras]>=version
        name = line.split(">=")[0].split("==")[0].split("<")[0].split("[")[0].strip()
        deps.append({"name": name, "spec": line})
    return deps


def get_workflow_files() -> list[dict]:
    """List GitHub Actions workflow files."""
    workflows = []
    wf_dir = PROJECT_ROOT / ".github" / "workflows"
    if not wf_dir.exists():
        return workflows
    for yml_file in sorted(wf_dir.glob("*.yml")):
        workflows.append({
            "name": yml_file.name,
            "size": yml_file.stat().st_size,
        })
    return workflows


def generate_report(sys_info: dict, deps: list[dict], workflows: list[dict]) -> str:
    """Generate the deployment report Markdown."""
    lines = []

    lines.append("# Tor-Bridges-Collector Deployment Report")
    lines.append("")
    lines.append("> Auto-generated by `scripts/generate_deployment_report.py`")
    lines.append("")

    # ── Environment Requirements ───────────────────────────────────────────
    lines.append("## 1. Environment Requirements")
    lines.append("")
    lines.append("### 1.1 Runtime Environment")
    lines.append("")
    lines.append("| Component | Minimum Version | Purpose |")
    lines.append("|-----------|----------------|---------|")
    lines.append("| Python | 3.10+ | Main application runtime |")
    lines.append("| Go | 1.21+ | Bridge probe, scheduler |")
    lines.append("| Rust | 1.70+ | Bridge-probe tool |")
    lines.append("| Zig | 0.11+ | Scanner module |")
    lines.append("| Git | 2.30+ | Version control |")
    lines.append("")

    lines.append("### 1.2 Current Build Environment")
    lines.append("")
    lines.append("| Property | Value |")
    lines.append("|----------|-------|")
    lines.append(f"| Python | {sys_info['python_version']} |")
    lines.append(f"| Platform | {sys_info['platform']} |")
    lines.append(f"| Architecture | {sys_info['architecture']} |")
    lines.append(f"| Go | {sys_info['go_version']} |")
    lines.append(f"| Rust | {sys_info['rust_version']} |")
    lines.append(f"| Zig | {sys_info['zig_version']} |")
    lines.append("")

    # ── Python Dependencies ────────────────────────────────────────────────
    lines.append("### 1.3 Python Dependencies")
    lines.append("")
    if deps:
        lines.append("| Package | Specification |")
        lines.append("|---------|--------------|")
        for dep in deps:
            lines.append(f"| `{dep['name']}` | `{dep['spec']}` |")
    else:
        lines.append("No requirements.txt found.")
    lines.append("")

    # ── Configuration ──────────────────────────────────────────────────────
    lines.append("## 2. Configuration Checklist")
    lines.append("")
    lines.append("### 2.1 Required Environment Variables")
    lines.append("")
    lines.append("| Variable | Required | Description |")
    lines.append("|----------|----------|-------------|")
    lines.append("| `CEREBRAS_API_KEY_1` | Yes | Cerebras AI API key (primary) |")
    lines.append("| `CEREBRAS_API_KEY_2` | No | Cerebras AI API key (fallback) |")
    lines.append("| `CEREBRAS_API_KEY_3` | No | Cerebras AI API key (fallback) |")
    lines.append("| `CF_ACCOUNT_ID_1` | Yes | Cloudflare account ID |")
    lines.append("| `CF_API_TOKEN_1` | Yes | Cloudflare API token |")
    lines.append("| `CF_AI_GATEWAY_URL_1` | Yes | Cloudflare AI Gateway URL |")
    lines.append("| `PORTKEY_API_KEY_1` | Yes | Portkey API key (pk- prefix recommended) |")
    lines.append("| `PORTKEY_VIRTUAL_KEY_1` | No | Portkey virtual key for provider routing |")
    lines.append("| `TELEGRAM_BOT_TOKEN` | No | Telegram bot token for notifications |")
    lines.append("| `TELEGRAM_CHAT_ID` | No | Telegram chat ID for notifications |")
    lines.append("")

    lines.append("### 2.2 GitHub Actions Secrets")
    lines.append("")
    lines.append("All environment variables above must be configured as GitHub Actions Secrets")
    lines.append("in the repository Settings > Secrets and variables > Actions.")
    lines.append("")

    # ── Deployment Steps ───────────────────────────────────────────────────
    lines.append("## 3. Deployment Steps")
    lines.append("")
    lines.append("### 3.1 Local Deployment")
    lines.append("")
    lines.append("```bash")
    lines.append("# 1. Clone the repository")
    lines.append("git clone <repository-url>")
    lines.append("cd Tor-Bridges-Collector")
    lines.append("")
    lines.append("# 2. Set up environment variables")
    lines.append("cp configs/env_template.sh .env")
    lines.append("# Edit .env with your API keys")
    lines.append("source .env")
    lines.append("")
    lines.append("# 3. Install Python dependencies")
    lines.append("pip install -r requirements.txt")
    lines.append("")
    lines.append("# 4. Run the main pipeline")
    lines.append("python main.py")
    lines.append("")
    lines.append("# 5. Run health check")
    lines.append("python scripts/ai_gateway_health_check.py")
    lines.append("```")
    lines.append("")

    lines.append("### 3.2 CI/CD Deployment (GitHub Actions)")
    lines.append("")
    lines.append("The project includes 4 automated GitHub Actions workflows:")
    lines.append("")
    if workflows:
        for wf in workflows:
            lines.append(f"- `{wf['name']}` ({wf['size']:,} bytes)")
    lines.append("")
    lines.append("1. **Quality Gate** (`torshield-ir.yml`): Syntax check, YAML lint, requirements validation, secret presence check")
    lines.append("2. **Main Pipeline** (`torshield-ir.yml`): Bridge collection, scoring, testing, export")
    lines.append("3. **Health Check** (`ai_gateway_health_check.yml`): Provider health verification")
    lines.append("4. **Self-Healing** (`ai_self_healing.yml`): Automatic error detection and recovery")
    lines.append("5. **Bridge Reranker** (`ai_bridge_reranker.yml`): AI-powered bridge re-ranking")
    lines.append("")

    # ── Health Verification ────────────────────────────────────────────────
    lines.append("## 4. Health Verification Procedures")
    lines.append("")
    lines.append("### 4.1 Provider Health Check")
    lines.append("")
    lines.append("```bash")
    lines.append("python scripts/ai_gateway_health_check.py --verbose")
    lines.append("```")
    lines.append("")
    lines.append("Expected output:")
    lines.append("- All 4 providers report `ok` or `degraded_local`")
    lines.append("- No `fail` status on primary providers")
    lines.append("- LocalAIEngine available as ultimate fallback")
    lines.append("")

    lines.append("### 4.2 Circuit Breaker Status")
    lines.append("")
    lines.append("Each provider has a circuit breaker that tracks consecutive failures.")
    lines.append("States: `closed` (healthy) → `open` (failing) → `half_open` (testing recovery)")
    lines.append("")
    lines.append("Check circuit breaker status via the provider dashboard:")
    lines.append("```bash")
    lines.append("python -c \"from torshield_ai_gateway import get_gateway; gw=get_gateway(); print(gw.health_stats())\"")
    lines.append("```")
    lines.append("")

    lines.append("### 4.3 Model Selector Status")
    lines.append("")
    lines.append("```bash")
    lines.append("python -c \"from torshield_ai_gateway import model_selector_status; print(model_selector_status())\"")
    lines.append("```")
    lines.append("")

    # ── Rollback Procedures ────────────────────────────────────────────────
    lines.append("## 5. Rollback Procedures")
    lines.append("")
    lines.append("### 5.1 Provider Failure")
    lines.append("")
    lines.append("If a provider fails:")
    lines.append("1. The circuit breaker opens automatically after 5 consecutive failures")
    lines.append("2. The gateway waterfall automatically skips open circuits")
    lines.append("3. If all providers fail, LocalAIEngine provides degraded fallback")
    lines.append("4. To manually reset a circuit breaker, restart the application")
    lines.append("")

    lines.append("### 5.2 Configuration Rollback")
    lines.append("")
    lines.append("1. Revert the environment variable to the previous value")
    lines.append("2. Restart the application or re-run the workflow")
    lines.append("3. Verify health check passes after rollback")
    lines.append("")

    # ── Troubleshooting ────────────────────────────────────────────────────
    lines.append("## 6. Common Issues and Solutions")
    lines.append("")
    lines.append("| Issue | Cause | Solution |")
    lines.append("|-------|-------|----------|")
    lines.append("| HTTP 401 from Portkey | Invalid API key | Check key format (pk- prefix), verify in Portkey dashboard |")
    lines.append("| HTTP 404 from Cerebras | Invalid model name | Model discovery auto-fixes; check CEREBRAS_MODELS fallback list |")
    lines.append("| HTTP 400 from CF AI Gateway | Invalid URL or model | Verify CF_AI_GATEWAY_URL includes account_id; model selector handles this |")
    lines.append("| HTTP 403 with error 1010 | Cloudflare bot protection | User-Agent header is auto-set; if persists, check IP reputation |")
    lines.append("| All providers failing | Network or credential issue | Check network connectivity, verify all API keys, run health check with --verbose |")
    lines.append("| Circuit breaker stuck open | Persistent provider failure | Check provider status externally; circuit auto-recovers after 5 minutes |")
    lines.append("| LocalAIEngine used often | All external providers down | Verify API keys and provider availability; LocalAIEngine is degraded mode |")
    lines.append("")

    # ── Package Information ────────────────────────────────────────────────
    lines.append("## 7. Package Information")
    lines.append("")
    lines.append("| Property | Value |")
    lines.append("|----------|-------|")
    lines.append("| Package Name | Tor-Bridges-Collector-main-ultra-quantum-vip-vip-super-ultra-vip-ultra-quantum-ultra-vip-ultra-quantum-ultra-quantum-vip |")
    lines.append("| Format | tar.gz |")
    lines.append("| Build Script | `packaging/build_package.sh` |")
    lines.append("| Verification | `sha256sum -c checksums.sha256` |")
    lines.append("| Contents | Source, configs, tests, workflows, documentation |")
    lines.append("")

    return "\n".join(lines)


def main():
    output_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("[Deploy] Gathering system information...")
    sys_info = get_system_info()

    print("[Deploy] Parsing dependencies...")
    deps = parse_requirements(PROJECT_ROOT / "requirements.txt")

    print("[Deploy] Scanning workflows...")
    workflows = get_workflow_files()

    print("[Deploy] Generating deployment report...")
    report = generate_report(sys_info, deps, workflows)

    output_path.write_text(report, encoding="utf-8")
    print(f"[Deploy] Report written to {output_path}")
    print(f"[Deploy] Size: {len(report):,} bytes")


if __name__ == "__main__":
    main()
