#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
# scripts/github_actions_env_bootstrap.sh
# ─────────────────────────────────────────────────────────────────────────────
# GitHub Actions adapter for the shared template-driven env bootstrap.
#
# The CircleCI bootstrap already contains the single source of truth for
# template parsing, Context/env override precedence, and safe .env generation.
# This wrapper reuses it, then exports the same values through $GITHUB_ENV so
# every later GitHub Actions step receives the numeric/time-window defaults and
# any explicitly-mapped secrets without hand-maintained YAML duplication.
# ════════════════════════════════════════════════════════════════════════════
set -euo pipefail

ENV_FILE="${1:-.env}"
TEMPLATE="${2:-configs/env_template.sh}"
GITHUB_ENV_FILE="${GITHUB_ENV:-}"

if [ -z "$GITHUB_ENV_FILE" ]; then
    echo "FATAL: GITHUB_ENV is not set; this script must run inside GitHub Actions" >&2
    exit 1
fi

bash scripts/circleci_env_bootstrap.sh "$ENV_FILE" "$TEMPLATE"

append_github_env() {
    local key="$1"
    local value="$2"
    local delimiter="TORSIELD_ENV_${key}_$$_${RANDOM}"

    {
        printf '%s<<%s\n' "$key" "$delimiter"
        printf '%s\n' "$value"
        printf '%s\n' "$delimiter"
    } >> "$GITHUB_ENV_FILE"
}

exported=0
while IFS= read -r line; do
    case "$line" in
        \#*|'')
            continue
            ;;
        *=*)
            key="${line%%=*}"
            encoded_value="${line#*=}"
            if [[ ! "$key" =~ ^[A-Z][A-Z0-9_]+$ ]]; then
                continue
            fi

            # Decode values emitted by circleci_env_bootstrap.sh via printf %q.
            # The encoded string is generated by our bootstrap script, not read
            # directly from the template, so this preserves special characters
            # while keeping arbitrary template code from being sourced.
            decoded_value=""
            eval "decoded_value=$encoded_value"
            append_github_env "$key" "$decoded_value"
            exported=$((exported + 1))
            ;;
    esac
done < "$ENV_FILE"

echo "✓ Exported $exported bootstrapped entries to GITHUB_ENV"
